import STUDENT from '../lib/img/student.jpg';
import TEACHER from '../lib/img/teacher.jpg';
import ADMIN from '../lib/img/admin.jpg';
export const STUDENT_FUNCTION_lIST=[
    {
        title:"信息设置",
        description:"根据自身情况修改信息",
        icon:'iconset-s',
        url:'/setting'
    },
    {
        title:"数据录入",
        description:"学生根据自己获奖情况录入自己综合素质的各个方面的数据",
        icon:'iconshujuluru',
        url:''
    },
    {
        title:"个人详情页",
        description:"针对每个学生的数据，详细展示学生各项数据的占比",
        icon:'icongerenxinxi',
        url:''
    },
    {
        title:"综合对比",
        description:"学生之间的综合比对，显示出对比分析结果",
        icon:'iconduibivs',
        url:''
    },
    {
        title:"综合排名",
        description:"系统数据库中所有学生综合排名，并通过各种条件进行筛选",
        icon:'iconpaiming',
        url:'/rank'
    },
    {
        title:"个人分析结果",
        description:"针对学生的每项数据，做出综合性分析",
        icon:'iconhuaxiangduibifenxi',
        url:''
    },
]
export const TEACHER_FUNCTION_lIST=[
    {
        title:"数据录入",
        description:"老师根据自己学生情况录入学生综合素质的各个方面的数据",
        icon:'iconshujuluru',
        url:''
    },
    {
        title:"学生个人详情页",
        description:"针对每个学生的数据，详细展示学生各项数据的占比",
        icon:'icongerenxinxi',
        url:''
    },
    {
        title:"学生综合对比",
        description:"学生之间的综合比对，显示出对比分析结果",
        icon:'iconduibivs',
        url:''
    },
    {
        title:"学生综合排名",
        description:"系统数据库中所有学生综合排名，并通过各种条件进行筛选",
        icon:'iconpaiming',
        url:''
    },
    {
        title:"审核学生综合成绩",
        description:"针对学生的每项数据，做出综合性分析",
        icon:'iconshenhe',
        url:''
    },
]
export const ADMIN_FUNCTION_lIST=[
    {
        title:"学生个人详情页",
        description:"针对每个学生的数据，详细展示学生各项数据的占比",
        icon:'icongerenxinxi',
        url:''
    },
    {
        title:"学生综合排名",
        description:"系统数据库中所有学生综合排名，并通过各种条件进行筛选",
        icon:'iconpaiming',
        url:''
    },
    {
        title:"综合素质评定元素修改",
        description:"教务管理员对综合评定元素及分数进行修改",
        icon:'iconshenhe',
        url:''
    },
]
export const CONTACT_LIST=[
    {
        title:"QQ:1223010592",
        icon:'iconqq',
        url:''
    },
    {
        title:"邮箱:1223010592@qq.com",
        icon:'iconyouxiang',
        url:''
    },
    {
        title:"电话:18827552328",
        icon:'icondianhua3',
        url:''
    },
]
export const LOGIN_LIST=[
    {
        title:"student",
        description:"学生登录，修改设置，录入数据，查看综合素质排名，个人详情，分析结果，学生对比分析详情",
        img:STUDENT,
        url:''
    },
    {
        title:"teacher",
        description:"老师登录，录入学生数据，查看综合排名，审核学生自主录入数据，学生详情，学生对比分析详情",
        img:TEACHER,
        url:''
    },
    {
        title:"administrator",
        description:"管理员登录，查看学生综合排名，修改综合素质评定元素及成绩",
        img:ADMIN,
        url:''
    }
]
export const LOGIN_ROLE={
    student:{
        name:'学生登录',
        placeholder:{
            name:'请输入学生学号',
            password:'请输入密码'
        }
        },
    teacher:{
        name:'老师登录',
        placeholder:{
            name:'请输入教师工号',
            password:'请输入密码'
        }
      },
    administrator:{
        name:'管理员登录',
        placeholder:{
            name:'请输入管理员工号',
            password:'请输入密码'
        }
    }
}
export const CHOSE_YEAR=[
    {key:"第一年度第一学期",value:1},
    {key:"第一年度第二学期",value:2},
    {key:"第二年度第一学期",value:3},
    {key:"第二年度第二学期",value:4},
    {key:"第三年度第一学期",value:5},
    {key:"第三年度第二学期",value:6},
    {key:"第四年度第一学期",value:7},
    {key:"第四年度第二学期",value:8}
]
